version: '3'

networks:
  laravel:

services:
  site_s1:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_s1
    ports:
      - "38080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php_s1
      - mysql_s1
    networks:
      - laravel

  mysql_s1:
    image: mysql:5.7.29
    container_name: mysql_s1
    restart: unless-stopped
    tty: true
    ports:
      - "30006:3306"
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: larauser
      MYSQL_PASSWORD: larap@ssw0rD
      MYSQL_ROOT_PASSWORD: larap@ssw0rD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php_s1:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_s1
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9013:9000"
    networks:
      - laravel

  composer_s1:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_s1
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php_s1
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm_s1:
    image: node:13.7
    container_name: npm_s1
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan_s1:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_s1
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql_s1
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
